### ISSUE TITLE
Upgrade impossible

### ISSUE THREAD

**Issue by Ackak** [zamentur/opensondage_ynh#12]
Hi,

I can't upgrade this app, becauce i have this message :
+ sudo service nginx 'reload#!/bin/bash'
Usage: nginx {start|stop|restart|reload|force-reload|status|configtest}
+ domain=
+ path=
+ admin=
+ language=
+ public_site=
+ legal=no
+ grep -q '"username": ""'
+ sudo yunohost user list --json
+ [[ ! 1 -eq 0 ]]
+ echo 'Wrong admin'
Wrong admin
+ exit 1
sh: 0: getcwd() failed: No such file or directory

It seems that the file of upgrade have the code of the file for installation (line 80)

**Comment by zamentur** [comment]
Thanks for this issue!
I have pushed a fix. When this fix will be available you should apply it.
Alternatively you can directly apply this:

>  public_site=$(sudo yunohost app setting opensondage public_site)
>  sudo service nginx reload
>  if [ $public_site = "No" ];
>  then
>    sudo yunohost app setting opensondage protected_uris -v "/admin,/index.php,/choix_date.php,/choix_autre.php,/infos_sondage.php,/scripts"
>  else
>    sudo yunohost app setting opensondage protected_uris -v "/admin/index.php,/admin/logs_studs.txt,/scripts"
>  fi
>  sudo yunohost app ssowatconf

**Comment by Ackak** [comment]
Ok, i will wait the fix ;)

**Comment by Ackak** [comment]
I did the update and it's now ok.
